#!/bin/bash

#GellMoxer 2.71.0

# Indonesia MJK
b='\033[1m';jl='SED';Jl='SE';jd='JAD';O='-';Sa=' ';u='\033[4m';bl='\E[30m';r='\E[31m';txcwq='te';vCl='f /';vCL='f ';kpg=']';itE='UT';ncret='tu';rna='UK';lvG='LA';amrk='USA';mrk='AS';Rk='S';kLo='0';kKo='OX';lkrq='}';sr='up-st';g='\E[32m';bu='\E[34m';iyj='I';m='\E[35m';c='\E[36m';w='\E[37m';fchj='💲';fchk='AND';gftd='ANG';zx='3';dDi='..';jVx='ard';xrsd=')';Sm='=';Xbo='FIX/b';FeC='e';FpC='p';hmOc='~';jbkn='trap';gHt='YA ';njroh='in';sp='set';rewyd='SAV';bxrs='r';ftry='{';dmck='D';endc='\E[0m';slnmb='...';nx='K';nb='AK ';jg='AN';bntLkgXc='*';mkljhgb='echo';azrcx='pil';df='cat';caft='A';cgfrt='A T';rpg='[';hXt='sdc';rpkd='(';smpkijo='cd';tryn='ur';twrq=':';nLL='null';trym='or';Trym='ERT';nmrt='ID';ghg='EG²';gsr='I G';jwbnunbkl='y';bsek='clear';ctrl='L';grr='|';gRt='H';dVe='dev';blue='\e[1;34m';zc='2';pRxb='$PRE';cxvz='ung ';wrt='lol';btlp='LAG';trc='sleep';kcxt='INT';kCx='IN';drtsw='mux';ptky='enjoy';ijhkxc='ls';xCs='st';oMh='home';itafg='figlet';ytwq=' JAT';ddh='H D';tRdc='ated';ertfd='Hit';umr='age';umt='AGE';erty='»';Sc='  ';ryt=' Y';ths='M';sMpk='cd $';ltrzs=';';bcxmn='ctr';cyan='\e[1;36m';smb='         ';kcvt='etik ';kJc='emul';zv='1';sRZ='GE';jwm='UH C';Hms='U';zljq='&';itYl='/';Xzc='P';vCd='ER';gfhjd='read';jmbutbnn='lagi';xcghjtr='exit';obh='l_c';eSa='m -r';CxX='C';vbcfg='Mund';red='\e[1;31m';smcv='   ';yll='\e[1;33m';xX='==========';xx='__________';
$knjsnsh$vsubxv$bnznbb$mkljhgb$Sa$oaoldb
###################################################
#    SCRIPT ini Sengaja Saya tulis seperti apa    #
#        yang ada di dalam Hati CEWEK             #
#  Makanya Sulit diPahami ataupun di Mengerti :v  #
#     Jadi Silahkan Recode Sesuka anda :v         #
#            WAHAI MASTAH RECODE!  SOK PRO! :)    #
#                                                 #
#  ,-Mario Bogell :v                              #
#                                                 #
###################################################
$jbkn$Sa$bcxmn$obh$Sa$kcxt
ctrl_c() {
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$vucoyy$fyxtcl$bsek$cguoir$szryoiu$ojouycV$AtKitv
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$plkutbjf$uhfdu$txcwq$bxrs$drtsw$O$sp$sr$trym$umr$kksnidh$joskdih
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$osoksijdhd$iijsysg$bsijbdg$sMpk$oMh$bsubbs$vbbxGu$KbhbHjj$yhRhvj
$tEdS$bxrs$eSa$vCL$xCs$trym$umr$itYl$bntLkgXc$oosjuzg$bjxbhu
$adEz$bxrs$eSa$vCl$xCs$trym$umr$itYl$kJc$tRdc$itYl$kLo$itYl$bntLkgXc
$ygfdf$bxrs$eSa$vCl$xCs$trym$umr$itYl$kJc$tRdc$itYl$bntLkgXc
$ooaijs$jbzvudn$bxrs$eSa$vCl$hXt$jVx$itYl$bntLkgXc$ijsjjbR
$oksuhdbid$bxrs$eSa$vCl$hXt$jVx$itYl$kLo$itYl$bntLkgXc
$xijsjsb$bxrs$eSa$vCl$hXt$jVx$zv$itYl$bntLkgXc$uhfyijc$ijvttcb
$osoojsh$ppsinsg$mhvzgC$mkskdug$bxrs$eSa$vCl$bntLkgXc$ygHfcjV
$yyfstig$okigT$bxrs$eSa$vCL$dDi$itYl$dDi$itYl$bntLkgXc$ihfgdij
$iksjubs$bzijjdug$bxrs$eSa$vCL$pRxb$Xbo$bsijsbsy$ijsjhv
$oksnuv$jdhuHbd$indJG$bxrs$eSa$vCL$hmOc$ksinxjv$ijsnzy
$iskjdub$kkskHJjs$bxrs$eSa$vCL$hmOc$Sa$itYl$dVe$itYl$nLL
$uigtrd$chihhyf$poinng$xtvjnv$gyhvxio$twrq$uhftd$dyibiy$xfhto
$oggoyD$JbgTfk$viiXsa$mkljhgb$Sa$lgouuk"$jyopF$czxopc$Sa$SqzxFt"
$xcakjeb$mNgvn$mkljhgb$Sa$O$FeC$Sa$ikajsCzv"$kakjshv$ths$FeC$ncret$pgutv$Gsfcq$Sa$CxX$rna$huyybc$farQyfl"|$gutgXd$wrt$df$jftihx
$ppucyS$Zsaxnb$Xczfvrt$trc$Sa$zc$Vcxrah$ogiyQw
$lakbsusbs$kakhsv$hvzBg$bsek$kksnhv$abudvk
$oiGxh$kmbceu$xcghjtr$houyx$ulmhy$mbljcl
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
}
cxzv=$ghxcvs$zv$phohut$afxyhv$ohhj
while [$llamjsg$yaytsvj$Sa$cxzv$Sa$opansgy$iajbzknx$uzxvv-lt$Sa$zc$lakbsuv$kanhyxh$papjeuv ];
do
$kskndib$gshkaodh$isjbshu$bduibdh$mkljhgb$iksjjduv$vsoshdv
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$iksjoksh$bidjdih$mkljhgb$Sa$O$FeC$Sa"$hduhdyg$bxvsfc$xx$xx$xx$cbzby$xx$xx$xx"|$vusuhy$wrt$df
$iksnihd$mkljhgb$Sa$O$FeC$Sa"$hisji$nxjbv$xX$xX$xX$xX$xX$xX$vhxbd$biGb"|$rtrac$wrt$df
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$iksishj$iiskisjs$itafg$Sa$iksisksj"$paposju$jsNjdh$sRZ$ctrl$ctrl$ths$kKo$vCd$oosjCf"|$oaiurg$wrt$df
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$jisjsh$hsjjsu$jisjsuh$mkljhgb$Sa$O$FeC$Sa"$tfDcy$cDbzhb$xX$xX$xX$xX$xX$xX"|$klsmbv$wrt$df
$ksknsib$oksmib$mkljhgb$Sa$O$FeC$Sa"$Vijdb$xx$kkskb$xx$xx$xx$kmsib$xx$xx"|$indjb$wrt$df
$euustgVHhhsa$mkljhgb$bdujdudh$idjjdhdih$isjisoo$abvSvhx
$xvtfg$rytsxz$mkljhgb$Sa$O$FeC$Sa$blue$Sa$jpkhbd"$nx$kcvt$g$erty$smcv$jwbnunbkl";
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$plkutbjf$uhfdu$txcwq$bxrs$drtsw$O$sp$sr$trym$umr$jjhuhgdm$oksijsu$bjsHsb
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$rteyuf$pljhms$ogsibfp$mkljhgb$Sa$guydohw$qxyivcx""
$gfhjd$Sa$O$FpC$Sa$atfxgec$atfxxc"$tfztfc$kofub$smb$fchj$ytrjo"$smcv$azrcx;
case $ksjihs$nznbxvvx$uajbsiv$pil$jjzbzvh$jjznvsh$olskjsb$cnznxbc in
$kksnsug$ksnhdub$bhzvsnj$jwbnunbkl$klanhdg$vnxbzc$nsnxbkz$papkisj)
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
:(){ $iaijsishdu$ooajzh$ikabhxi$cvzbxcca$ayyvdh$vsujvzvjjdbv
$oksnihs$hhsjkhs$jajbjsug$czbjbxjj$nnsjjbs$kmsjhbx$zxxxbn$utrxcbj
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$jajsbgj$vvznnh$teayuef$qwsczhg$usjbvzu$llamngzkz$jjabgz :|: & $havcfzb$jnnsugz
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
}; $ijajhgs$kksjbg$ikxngyz$jsjbxgus$qwsZxv$iiksnoohs$vbxmmbz
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$rytryg$dgfazx$cgcdhdl$mkljhgb$Sa$purgogi"$goyiflgi$gjyckc$lpovur"
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$plkutbjf$uhfdu$txcwq$bxrs$drtsw$O$sp$sr$trym$umr$yhvdyf
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$mkljhgb$Sa$O$FeC$Sa$igufyS"$ofuftjno$smb$ertfd$cxvz$vbcfg$tryn$slnmb"|$wrt$df
$ppgisf$qarzcc$cguiyyF$trc$Sa$zc$ooifj$vjjcuco$zfvfr
$adxzcE$fgdtRf$yicydAs$mkljhgb$Sa$pjhpigu$aciwuW"$armxK$smcv$smb$smcv$smb$zx$gogyh$Djxczs"|$hoif$ygcbnD$wrt$df$YvjyRdh
$oosppy$aabdko$qawhx$trc$Sa$zv$rrtfsz$giytxC
$yijff$yuhdX$mkljhgb$Sa$ifjdC"$yoiuXzm$smcv$smb$smcv$smb$zc$jcjcyh$xSzcfr"|$hiuXfz$wrt$df$Jcrma
$jsihd$trc$Sa$zv$vxjbhj$oosljhs$yttass$ogiyvX$iokhraq
$attdytcg$cttudo$Xragw$mkljhgb$Sa$vhurvd$gvvsAs"$oCean$Bnrmg$smcv$smb$smcv$smb$zv$iufsh$adxtui"|$qtewrx$fXcsgi$wrt$df$giuyp
$olakjhs$jsbgs$llannbd$trc$Sa$zv$kosnh$oksnhgsi
$ppajhd$mkljhgb$Sa$O$FeC$Sa"$yoigtV$Gudsjt$cewulq$smb$fchk$cgfrt$nmrt$nb$jl$gftd$ytwq$jwm$kcxt$caft$puftb"|$Yufej$wrt$df$giuti$cgysgD$frzRdg
$lpaonbs$trc$Sa$zv$jbsvvz$ijsnbvs$kkskva
$posjud$mkljhgb$Sa$O$FeC$Sa"$zadxr$smb$jd$gsr$caft$amrk$ddh$ghg$nx$jg$ryt$caft$slnmb"|$gudt$wrt$df$jfyugke
$ijaugs$oozjhd$trdzyg$trc$Sa$zc$kjsjbhks
$ppajubd$kodiulD$itafg$Sa$pllnrw"$uCfs$giyjfmv$nb$Hms$Sc$Sa$gRt$caft$ths$iyj$ctrl"|$ujroog$zjgeujc$ygddhDd$wrt$df$upittv
$ucui$hudgjhc$hlkjgcc$chxtcjs$axfgvmlk$fyioy$iofyjv
$xffvjj$axrrd$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$azrgh
$juyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth
$lhifyg$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg
$lkjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$olloj$zvsfv$dytuki$phuvxsl
$uckfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$olloj$zvsfgv$rsgg
$ycyy$ykk$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh
$sdxhcg$olloj$zvsfv$dytu$ycyy$ykk$adhkhy$agcxt
$yrsttzxc$hlkjgcc$chxtcjs$axfgvmlk$fyioy$tyreyx
$ohfvjj$axrrd$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fygyh
$adfyg$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$cctytr
$iytkhy$agcxt$sdxhcg$olloj$zvsfv$dytuki$phuvxtd
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$olloj$cctyrt
$kgfy$ykk$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrdh
$mbchcg$olloj$zvsfv$dytu$ycyy$yhkk$adhkhy$agctre
$hlkjgcc$chxtcjs$axfgvmlk$fyioy$xffvjj$axrrd
$xxcvgdf$xznff$sdxhcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$omlloj$zvsfv$dygtu$adhkhy
$agcxt$sdxhcg$ollbj$zvsfv$dytuki$phuvxsl$uckfi
$werxyy$ykfdk$adhkhy$agcxt$sdxhcg$olloj$zvsfv$dhytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$guiloj
$tydhjf$oixuft$zvsfhv$dydtu$ycyy$ykk$adhkhy$agcxt$yrsttzxc
$hlkjgcc$chxtcjs$axfgvmlk$fyioy$ohfvjj$axrrd$zxcvgdf$udyhugj
$osoksijdhd$iijsysg$bsijbdg$sMpk$oMh$bsubbs$vbbxGu$KbhbHjj$yhRhvj
$djRs$bxrs$eSa$vCL$xCs$trym$umr$itYl$bntLkgXc$oosjuzg$bjxbhu
$ftErs$bxrs$eSa$vCl$xCs$trym$umr$itYl$kJc$tRdc$itYl$kLo$itYl$bntLkgXc
$tdEs$bxrs$eSa$vCl$xCs$trym$umr$itYl$kJc$tRdc$itYl$bntLkgXc$uugdfyg
$ooaijs$jbzvudn$bxrs$eSa$vCl$hXt$jVx$itYl$bntLkgXc$ijsjjbR
$oksuhdbid$bxrs$eSa$vCl$hXt$jVx$itYl$kLo$itYl$bntLkgXc$yyujvRc
$xijsjsb$bxrs$eSa$vCl$hXt$jVx$zv$itYl$bntLkgXc$uhfycdvc
$osoojsh$ppsinsg$mhvzgC$mkskdug$bxrs$eSa$vCl$bntLkgXc$ftVyRv
$yyfstig$okigT$bxrs$eSa$vCL$dDi$itYl$dDi$itYl$bntLkgXc$ihfgdij
$iksjubs$bzijjdug$bxrs$eSa$vCL$pRxb$Xbo$bsijsbsy$ijsjhvhfd
$oksnuv$jdhuHbd$indJG$bxrs$eSa$vCL$hmOc$ksinxjv$ijsnzygvy
$iskjdub$kkskHJjs$bxrs$eSa$vCL$hmOc$Sa$itYl$dVe$itYl$nLL$uuvrrxv
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi$iihtff
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$xznff$sdxhcg$etsaf$yyxctj$aihrgh$sdyyfi$yioytf
$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fygyh$adfyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$furxig$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvu
$iytkhy$agcxt$sdxhcg$olloj$zvshfv$dytuki$phuvxtd$pwqfi
$ycyy$ykk$adhkhy$agcxt$sdxhcg$uifkcbloj$zvofvu
$sdxhcyg$etsaf$yyxctj$azrdh$mbchcg$ollfdoj
$zvsfv$dytu$ycyy$ykk$adhkhy$agctre$ytdjut$agxgj
$axrrd$zxcvgdf$xznff$etsaf$yyxctj$aihrgh
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fygyh
$adfyg$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhchhg$xzvsfvu
$iytkhy$agcxt$sdxhcg$vcolloj$zvsfvk$dytuki$phuvxtd
$pwqfi$ycyy$hauykk$adhkhy$agcvtxt$zvsfvu$thpuagf
$gkgfy$ykk$adhkhy$ajgcxt$sdxhcgd$ejltsa$yyxctj$azrdh
$mbchcfg$hoolloj$zvsfv$dytu$ycyy$ykkiwu$adhkhy$agctre
$hlkjgcc$chxtcjs$axfgvmlk$fyioy$xffvjj$axrrd
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrdg$zxcgvgdf$xrznff$qrrgjh$amrklhg$lkjgcc
$chxtgcjs$axfgvmlk$fyioy$sdxhcg$olloj$sov$dgytuoy$adhkhy
$okakush$olakksh$zxxcbb$azxbxjh$kksnhs$twrq$kksjvgs$kksngd
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrdg$zxcgvgdf$xrznff$qrrgjh$amrklhg$lkjgcc
$chxtgcjs$axfgvmlk$fyioy$sdxhcg$olloj$sov$dytuoy$adhksh
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklxs
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$icvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$uhiikf
$ldyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugpsj
$xdfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$kwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsh
$fdtkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$nmqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$sdfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$zqchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$lfkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$ptcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$wroytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$itfvjj$axrrd$zxcvgdf$xznff$qrrgjh$smcvc$smbv
$ijshys$ysgsuu$xcghjtr$kabahvs$okshuev$psjixz
;;
$oksksu$okskbs$bntLkgXc$vusbhb)$plajud$gBjags$mkljhgb$Sa$O$FeC$Sa$cyan$Sa$yyracv"$gshjXcv$smcv$smcv$Sc$O$Sm$Sa$Jl$Xzc$Trym$kCx$gHt$jg$dmck$caft$Sa$Rk$caft$lvG$gRt$Sa$kCx$Xzc$itE$Sa$Sm$O"
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$plkutbjf$uhfdu$txcwq$bxrs$drtsw$O$sp$sr$trym$umr$ijbucc$okminvtc
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj$ugfuhhj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt$yuhifRc
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi$yugtvfh$yucxyh
$osoksijdhd$iijsysg$bsijbdg$sMpk$oMh$bsubbs$vbbxGu$KbhbHjj$yhRhvj
$ujgZ$bxrs$eSa$vCL$xCs$trym$umr$itYl$bntLkgXc$oosjuzg$bjxbhu
$yFgA$bxrs$eSa$vCl$xCs$trym$umr$itYl$kJc$tRdc$itYl$kLo$itYl$bntLkgXc
$yhfD$bxrs$eSa$vCl$xCs$trym$umr$itYl$kJc$tRdc$itYl$bntLkgXc$txfujf
$ooaijs$jbzvudn$bxrs$eSa$vCl$hXt$jVx$itYl$bntLkgXc$ijsjjbR
$oksuhdbid$bxrs$eSa$vCl$hXt$jVx$itYl$kLo$itYl$bntLkgXc$yuhfubhj
$xijsjsb$bxrs$eSa$vCl$hXt$jVx$zv$itYl$bntLkgXc$yftjigj$srtvhuj
$osoojsh$ppsinsg$mhvzgC$mkskdug$bxrs$eSa$vCl$bntLkgXc$yuhfuijfg
$yyfstig$okigT$bxrs$eSa$vCL$dDi$itYl$dDi$itYl$bntLkgXc$ihfgdij
$iksjubs$bzijjdug$bxrs$eSa$vCL$pRxb$Xbo$bsijsbsy$ijsjhv
$oksnuv$jdhuHbd$indJG$bxrs$eSa$vCL$hmOc$ksinxjv$ijsnzy
$iskjdub$kkskHJjs$bxrs$eSa$vCL$hmOc$Sa$itYl$dVe$itYl$nLL
$ijjijng$ioknuvf$iijbycc$twrq$ijjugv$fgGuhf$jhhgte$ugduiffh
$agcxtf$sdxhcg$orlloj$zvgsfv$dytuki$phuvl$uckfi$yuguijh7yh
$werxyy$cznykk$adhkhy$agcxht$sdtxhcg$ouwlloj$zvhsfv$dytu
$adhkhy$agcxtb$sdxhcg$etsaf$yyxctj$azrgh$sxhcg$maklloj
$tydhjf$oixuft$zvgsfuv$dytu$yzcyy$yklkk$ohkhy$aigcxt
$zxcvgdf$xznff$sdxhcg$etsaf$yyxctj$aihrgh$kknsbg
$sdyyfi$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$ltokfz$fyugyh
$adfyg$xffvjj$axrrd$zxcvgdf$xzunff$qrrgjh$amrklyt
$qwrjgcc$chxtcjs$axfgvmlk$fyioy$sdxhcgh$yklloyj$zovsfvu
$iytkhy$agcxt$sdxuhcg$haluoj$zvspfv$dytuki$phuvx
$pwqfi$ycyy$ykk$adhkhy$agcxt$sdxhcg$aploj$sgsfvuh
$kgfy$ykqfk$adhkhy$aqgcxt$sdpxhcg$etsaf$yiyxctj$azrdh
$mbchcg$olloj$zvssfv$dytu$ycyy$ykysk$adhkhy$agctre
$hlkjgcc$chxhtcjs$axfgvmlk$fyioy$xffvjj$kaxrrd
$xxcvgdf$xznff$sdxhgcg$etsaf$yyxctj$azrgh$juyyfi
$yioytf$tdtyx$aqsrr$tyjfgo$aexdtx$atokfz$fyth$lhifyg
$xffvjj$axrrd$zxcvgdf$xznff$qrrgjh$amrklhg$lkjgcc
$chxtcjs$axfgvmlk$fyioy$sdxhcg$olloj$zvsfvhu$gdytu$adhkhy
$agcxt$sdxhcgwg$oblloj$zvsfvv$dytuki$phuvxsl$uckfi
$werxyy$ykk$adhuwkhy$agcxt$sdhxhcg$klolloj$zvsfv$dytu
$adhkhy$agcxt$sdxhcg$etsaf$yyxctj$azrgh$sdxhcg$olloj
$tydhjf$oixuft$zvgsfv$dytu$ycyy$ydukk$adhkhy$apogcxt
$xxcvgdf$xznff$sdxhcg$etsaf$yyxgctj$azrgh$juyyfi
$plaubqh$vzxvbns$mkljhgb$Sa$O$FeC$Sa$g$Sa$plakbxb$mbzxvfg"$xcvbzgan$rtayeurc$cxzbsA$smcv$smb$smcv$O$Sm$Sa$ths$mrk$rna$Sa$btlp$iyj$Sa$Sm$O$kkskjbd$mmsbbx"
$rtacbzc$zxacbzg$jksbbd$vvdbsa$mkljhgb$Sa$O$FeC$Sa$ppaubey"$oaoksm$xx$cahzbd$xx$azzvm$xx$plaijs$xx$mmabx$xx$lajhgd"|$iajjsuv$hudndidk$wrt$df$qpnsuhs$ujsnsu
esac
done
done
